PROGRAM NAMESPACE
IMPLICIT NONE
INTEGER I,J,N
CHARACTER*15::NAME(10)
CHARACTER*1:: SEX(10)
INTEGER::AGE(10)
REAL::WEIGHT(10)
PRINT*,"ENTER HOW MANY PERSON(S):"
READ*,N
DO I=1,N
  PRINT*,"ENTER NAME :"
  READ*,NAME(I)
  PRINT*,"ENTER AGE :"
  READ*,AGE(I)
  PRINT*,"ENTER WEIGHT :"
  READ*,WEIGHT(I)
  PRINT*,"ENTER SEX :"
  READ*,SEX(I)
  END DO
 DO I=1,N
   !WRITE(*,2)
   WRITE(*,1)NAME(I),AGE(I),WEIGHT(I),SEX(I)
   1 FORMAT(a15,4x,i10,3x,f10.2,4x,a1)
   END DO
 END

 !!author murad-pc